version: "3.5"

services:
  php:
    user: ${APP_UID:-1000}:${APP_GID:-1000}
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    restart: always
    tty: true
    expose:
      - "8000/tcp"
    networks:
      - default
      - test_management
    ports:
      - "${APP_PORT:-8000}:8000"
    command: ["sh", "-c", "symfony serve"]
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  #  postgres:
  #    image: postgres:15.0-alpine
  #    restart: always
  #    ports:
  #      - "${DB_EXTERNAL_PORT:-5432}:5432"
  #    environment:
  #      POSTGRES_DB: ${DB_DATABASE:-test-management}
  #      POSTGRES_USER: ${DB_USERNAME:-root}
  #      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  #    volumes:
  #      - 'postgres_data:/var/lib/postgresql/data'

  ##> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test-management}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  postgres_data:

  ###> doctrine/doctrine-bundle ###
  database_data:
    ###< doctrine/doctrine-bundle ###
    driver: local

networks:
  test_management:
    external: true
    name: local_test_management
